ALTER TABLE `market_data`
  ADD COLUMN IF NOT EXISTS `external_property_id` VARCHAR(191) NULL,
  ADD COLUMN IF NOT EXISTS `title` VARCHAR(512) NULL,
  ADD COLUMN IF NOT EXISTS `bedrooms` INT NULL,
  ADD COLUMN IF NOT EXISTS `luxury_level` VARCHAR(128) NULL,
  ADD COLUMN IF NOT EXISTS `price_category` VARCHAR(128) NULL,
  ADD COLUMN IF NOT EXISTS `market_segment` VARCHAR(128) NULL,
  ADD COLUMN IF NOT EXISTS `image_url` VARCHAR(1024) NULL,
  ADD COLUMN IF NOT EXISTS `source_url` VARCHAR(1024) NULL,
  ADD COLUMN IF NOT EXISTS `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3);
